"use client";
// import { Cabin } from "next/font/google";
import {Archivo} from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Navbar from "./_components/navbar";
import { usePathname } from "next/navigation";
import { useState } from "react";
import {CartContext} from "./_context/CartContext"
import { SessionProvider } from "./_context/SessionContext";

const cabin = Archivo({ subsets: ["latin"] });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname();
  const [updateCart, setUpdateCart] = useState(false);
  const showComponents = params == '/signin' ||  params == '/signup'? false : true; 
  return (
    <html lang="en">

        <body className={cabin.className}>
          <SessionProvider>
          <CartContext.Provider value={{updateCart, setUpdateCart}}>
         {showComponents && <Navbar/> }
          
       <>{children} </> 
       {showComponents && <Footer/> }
       </CartContext.Provider>
       </SessionProvider>
        </body>
    </html>
  );
}
